<a href="https://colab.research.google.com/github/kireayom16/classfiles/blob/main/practica4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

matriz1 = np.random.randint(1, 11, (3, 3))
matriz2 = np.random.randint(1, 11, (3, 3))

print("Matriz 1:", matriz1)
print("\nMatriz 2:", matriz2)


Matriz 1: [[9 9 6]
 [5 3 7]
 [1 5 7]]

Matriz 2: [[ 8  3  3]
 [10  8  5]
 [ 8  5  7]]


In [8]:
# Suma ambas matrices
suma = matriz1 + matriz2
print("Suma de matrices:",suma)


# Resta la segunda matriz de la primera
resta = matriz1 - matriz2
print("Resta (Matriz1 - Matriz2):",resta)

# Multiplica la primera matriz por 2
multiplicacion_x2 = matriz1 * 2
print("Multiplicación de Matriz1 por 2:",multiplicacion_x2)

# Multiplicación matricial entre las dos matrices
multiplicacion_matricial = np.dot(matriz1, matriz2)
print("Multiplicación matricial:",multiplicacion_matricial)


Suma de matrices: [[17 12  9]
 [15 11 12]
 [ 9 10 14]]
Resta (Matriz1 - Matriz2): [[ 1  6  3]
 [-5 -5  2]
 [-7  0  0]]
Multiplicación de Matriz1 por 2: [[18 18 12]
 [10  6 14]
 [ 2 10 14]]
Multiplicación matricial: [[210 129 114]
 [126  74  79]
 [114  78  77]]
